name: PR-Comment

on: issue_comment

jobs:
  pr_commented:
    name: PR comment
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          gh pr checkout ${{ github.event.issue.number }}
          clang-format-12 --version
          clang-format-12 -i main.cpp
          git diff --exit-code
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
