name: PR-Comment

on: issue_comment

jobs:
  pr_commented:
    name: PR comment
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          echo "Comment on PR #${{ github.event.issue.number }}"
          ls -alF
          pwd
