name: Style-Check

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  style_check:
    name: Style-Check
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Run clang-format
        run: .ci/run_clang_format.sh
      - name: Check diff
        run: |
          git diff --exit-code --color
      - name: Save PR number
        if: always()
        run: |
          mkdir -p ./pr
          echo ${{ github.event.number }} > ./pr/NR
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: pr
          path: pr/
